# Generated by Django 2.2.2 on 2022-04-20 08:35

import admins.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, verbose_name='Email')),
                ('is_teacher', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, error_messages={'max_length': '11 Numbers required.'}, help_text='Required. 11 Nigeria Phone Numbers.', max_length=11, unique=True, validators=[admins.models.numeric_validator], verbose_name='Phone Number')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', admins.models.BaseManager()),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('classteacher', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1500)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbr', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProgramme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.FileField(upload_to='programme-reports')),
                ('_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.Class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=55, validators=[admins.models.alpha_validator], verbose_name='First Name')),
                ('lastname', models.CharField(max_length=55, validators=[admins.models.alpha_validator], verbose_name='Last Name')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('state', models.CharField(max_length=20)),
                ('lga', models.CharField(max_length=50, verbose_name='Local Government Area')),
                ('hometown', models.CharField(max_length=50, verbose_name='Home Town')),
                ('image', models.ImageField(blank=True, upload_to='teacher-images')),
                ('guardianname', models.CharField(max_length=55, validators=[admins.models.alpha_validator], verbose_name='Guardian Name')),
                ('guardianphonenumber', models.CharField(error_messages={'max_length': '11 Numbers required.'}, help_text='Required. 11 Nigeria Phone Numbers.', max_length=11, validators=[admins.models.phone_validator], verbose_name='Phone Number')),
                ('guardianemail', models.EmailField(max_length=254)),
                ('classaverage', models.FloatField()),
                ('classposition', models.IntegerField()),
                ('_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admins.Class')),
                ('subjects', models.ManyToManyField(blank=True, to='admins.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=55, validators=[admins.models.alpha_validator], verbose_name='First Name')),
                ('lastname', models.CharField(max_length=55, validators=[admins.models.alpha_validator], verbose_name='Last Name')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('phonenumber', models.CharField(error_messages={'max_length': '11 Numbers required.'}, help_text='Required. 11 Nigeria Phone Numbers.', max_length=11, unique=True, validators=[admins.models.phone_validator], verbose_name='Phone Number')),
                ('state', models.CharField(max_length=20)),
                ('lga', models.CharField(max_length=50, verbose_name='Local Government Area')),
                ('hometown', models.CharField(max_length=50, verbose_name='Home Town')),
                ('image', models.ImageField(blank=True, upload_to='teacher-images')),
                ('accountnumber', models.CharField(blank=True, max_length=10, validators=[admins.models.numeric_validator])),
                ('accountname', models.CharField(blank=True, max_length=255)),
                ('bank', models.CharField(blank=True, max_length=100)),
                ('staff_type', models.CharField(max_length=2)),
                ('status', models.BooleanField(default=True)),
                ('position', models.CharField(max_length=30)),
                ('programme', models.ManyToManyField(blank=True, to='admins.TeacherProgramme')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admins.Class')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=1500)),
                ('attachment', models.FileField(upload_to='mail')),
                ('read', models.BooleanField(default=False)),
                ('flag', models.CharField(choices=[('u', 'URGENT'), ('i', 'INFO')], max_length=2)),
                ('_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_from', to=settings.AUTH_USER_MODEL)),
                ('to', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='event-images')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.Event')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='subject',
            field=models.ManyToManyField(blank=True, to='admins.Subject'),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=55, validators=[admins.models.alpha_validator])),
                ('lastname', models.CharField(max_length=55, validators=[admins.models.alpha_validator])),
                ('image', models.ImageField(blank=True, upload_to='admin-images')),
                ('phonenumber', models.CharField(error_messages={'max_length': '11 Numbers required.'}, help_text='Required. 11 Nigeria Phone Numbers.', max_length=11, unique=True, validators=[admins.models.phone_validator], verbose_name='Phone Number')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
