# Generated by Django 2.2.2 on 2022-04-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='classteacher',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
