# Generated by Django 2.2.2 on 2022-04-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_auto_20220420_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_type',
            field=models.CharField(choices=[('t', 'TEACHING'), ('n', 'NON-TEACHING')], max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='classaverage',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='classposition',
            field=models.IntegerField(blank=True),
        ),
    ]
