# Generated by Django 2.2.2 on 2022-04-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_auto_20220420_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprogramme',
            name='report',
            field=models.FileField(blank=True, upload_to='programme-reports'),
        ),
    ]
