# Generated by Django 2.2.2 on 2022-04-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_auto_20220421_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='classaverage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='classposition',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardianname',
            field=models.CharField(max_length=55, verbose_name='Guardian Name'),
        ),
    ]
