# Generated by Django 2.2.2 on 2022-04-22 15:09

import admins.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0008_auto_20220422_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, error_messages={'max_length': '11 Numbers required.'}, help_text='Required. 11 Nigeria Phone Numbers.', max_length=11, null=True, unique=True, validators=[admins.models.numeric_validator], verbose_name='Phone Number'),
        ),
    ]
