# Generated by Django 2.2.2 on 2022-04-22 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0009_auto_20220422_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
