# Generated by Django 2.2.2 on 2022-04-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0010_remove_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='attachment',
            field=models.FileField(blank=True, upload_to='mail'),
        ),
    ]
