# Generated by Django 2.2.2 on 2022-04-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0012_auto_20220423_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='residential_address',
            field=models.TextField(default='Prefer not to say', max_length=1000),
        ),
        migrations.AddField(
            model_name='student',
            name='residential_address',
            field=models.TextField(default='Prefer not to say', max_length=1000),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
