# Generated by Django 2.2.2 on 2022-05-15 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0013_auto_20220425_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='mail',
            name='to',
        ),
        migrations.AddField(
            model_name='mail',
            name='to',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
