# Generated by Django 2.2.2 on 2022-05-15 12:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0014_auto_20220515_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='to',
        ),
        migrations.AddField(
            model_name='mail',
            name='to',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('deleted user'), to=settings.AUTH_USER_MODEL),
        ),
    ]
