# Generated by Django 2.2.2 on 2022-05-15 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0016_auto_20220515_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='residential_address',
            field=models.TextField(blank=True, default='Prefer not to say', max_length=1000),
        ),
    ]
