# Generated by Django 2.2.2 on 2022-05-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0017_auto_20220515_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='teacher-images'),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='student-images'),
        ),
    ]
